### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by matheusjardimb** [fellipeh/iugu-python3#1]
As instruções de pip install apontam para o projeto original.

Já é possível instalar a lib através do pip?

**Comment by andrekiffer** [comment]
+1

**Comment by fhbash** [comment]
Olá @matheusjardimb e @andrekiffer 

Você pode tentar usando:

```
$ pip3 install iugu-python3
```

Ou instalar manualmente este projeto:

```
$ git clone https://github.com/fellipeh/iugu-python3.git
$ pip3 install -e iugu-python3

```

Deixe um comentário caso não consiga
